# Generated by Django 4.2.2 on 2023-06-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_salesorder_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='customer_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_address',
            field=models.TextField(default=''),
        ),
    ]
